apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootdummies
  labels:
    app: springbootdummies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootdummies
  template:
    metadata:
      labels:
        app: springbootdummies
    spec:
      containers:
      - name: springboot
        image: rjayasinghe/springbootdummies:latest
        ports:
        - containerPort: 8080
