version: '2.1'
services:
  'springboot':
    hostname: tartaros-springboot.synyx.coffee
    build: .
    ports:
        - "8080:8080"
    environment:
        - SPRING_DATASOURCE_URL=jdbc:mariadb://tartaros-database.synyx.coffee:3306/fluff?useUnicode=yes&characterEncoding=utf8
    links:
        - mariadb:tartaros-database.synyx.coffee
  'mariadb':
    hostname: tartaros-database.synyx.coffee
    image: mariadb
    ports:
        - "3306:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=fluff
        - MYSQL_USER=fluff
        - MYSQL_PASSWORD=fluff
