apiVersion: v1
kind: Service
metadata:
  labels:
    app: springbootdummies
  name: springbootdummies
  namespace: jayasinghe
spec:
  ports:
  - name: http
    port: 6666
    protocol: TCP
    targetPort: 8080
  selector:
    app: springbootdummies

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: springbootdummies
  name: springbootdummies
  namespace: jayasinghe
spec:
  rules:
  - host: k8s-springbootdummies.synyx.coffee
    http:
      paths:
      - backend:
          serviceName: springbootdummies
          servicePort: 6666
        path: /

